### ISSUE TITLE
Fans do not start at a stated threshold... Not even sure they start at all.

### ISSUE THREAD

**Issue by fakamaz** [vmatare/thinkfan#192]
Here's an example from the config file:
```
tp_fan /proc/acpi/ibm/fan

hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp3_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp4_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp5_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp2_input
hwmon /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp1_input
hwmon /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp2_input

(0,     0,      40)
(1,     38,     44)
(2,     42,     48)
(3,     46,     52)
(4,     50,     56)
(5,     54,     60)
(6,     58,     64)
(7,     62,     68)
(127,   66,     32767)
```
Status is:
```
thinkfan.service - simple and lightweight fan control program
     Loaded: loaded (/lib/systemd/system/thinkfan.service; enabled; vendor pres>
     Active: active (running) since Mon 2022-07-11 18:39:23 CEST; 39min ago
   Main PID: 31971 (thinkfan)
      Tasks: 1 (limit: 18863)
     Memory: 260.0K
     CGroup: /system.slice/thinkfan.service
             └─31971 /usr/sbin/thinkfan -q

Jul 11 18:39:23 ThinkPad-L430 systemd[1]: Starting simple and lightweig>
Jul 11 18:39:23 ThinkPad-L430 thinkfan[31970]: thinkfan 0.9.1 starting.>
Jul 11 18:39:23 ThinkPad-L430 systemd[1]: Started simple and lightweight>
```
But the temperature is still high and I have a feeling the fans do not start when stated. So how can I fix this?

**Comment by vmatare** [comment]
Well, first of all you should try and find out what the situation actually is. So when you feel like thinkfan isn't reacting to your temperatures the way you expect it to, run:
```bash
sensors
pkill -usr1 thinkfan
journalctl -el -u thinkfan
```
and post the output here.

**Comment by fakamaz** [comment]
**Sensors**: 

thinkpad-isa-0000
Adapter: ISA adapter
fan1:           0 RPM

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.84 V  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +77.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:        +75.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:        +77.0°C  (high = +87.0°C, crit = +105.0°C)
Core 2:        +70.0°C  (high = +87.0°C, crit = +105.0°C)
Core 3:        +72.0°C  (high = +87.0°C, crit = +105.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +74.0°C  (crit = +88.0°C)
temp2:        +59.0°C  (crit = +88.0°C)

**pkill** - produced an error when run as-is, when run as sudo - showed nothing...
**journalctl**:
-- Logs begin at Mon 2022-07-18 10:13:58 CEST, end at Mon 2022-07-18 11:33:58 C>
Jul 18 10:14:09 -ThinkPad-L430 systemd[1]: Starting simple and lightweig>
Jul 18 10:14:10 -ThinkPad-L430 thinkfan[1224]: thinkfan 0.9.1 starting...
Jul 18 10:14:10 -ThinkPad-L430 systemd[1]: Started simple and lightweigh>
Jul 18 11:33:58 -ThinkPad-L430 thinkfan[1262]: current temperatures: (75>

**Comment by vmatare** [comment]
That seems very strange to me. Unfortunately your log output is truncated, so I can't see what fan speed thinkfan has calculated. Can you please do the following during high temps:
```bash
sudo pkill -usr1 thinkfan
sudo journalctl --no-pager -el -u thinkfan
sudo cat /proc/acpi/ibm/fan
sudo bash -c 'for f in /sys/module/thinkpad_acpi/parameters/*; do echo $f; cat $f; echo; done'
```
Normally we should see the calculated fan speed (127 at ~70°C) in the log message and the corresponding "level disengaged" in `/proc/acpi/ibm/fan`. If both are the case, then something must be wrong with your `thinkpad_acpi` kernel module. If one of those things is not the case, there must be something wrong with thinkfan.

**Comment by fakamaz** [comment]
**And here's on higer temps:**

-- Logs begin at Thu 2022-07-21 10:15:24 CEST, end at Thu 2022-07-21 18:54:10 CEST. --
Jul 21 10:15:35 -ThinkPad-L430 systemd[1]: Starting simple and lightweight fan control program...
Jul 21 10:15:36 -ThinkPad-L430 thinkfan[1298]: thinkfan 0.9.1 starting...
Jul 21 10:15:36 -ThinkPad-L430 systemd[1]: Started simple and lightweight fan control program.
Jul 21 18:53:57 -ThinkPad-L430 thinkfan[1333]: current temperatures: (87, 83, 87, 83, 84, 86, 55)

status:		enabled
speed:		0
level:		disengaged
commands:	level <level> (<level> is 0-7, auto, disengaged, full-speed)
commands:	enable, disable
commands:	watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds))

/sys/module/thinkpad_acpi/parameters/brightness_enable
2

/sys/module/thinkpad_acpi/parameters/brightness_mode
4

/sys/module/thinkpad_acpi/parameters/dbg_bluetoothemul
0

/sys/module/thinkpad_acpi/parameters/dbg_uwbemul
0

/sys/module/thinkpad_acpi/parameters/dbg_wlswemul
0

/sys/module/thinkpad_acpi/parameters/dbg_wwanemul
0

/sys/module/thinkpad_acpi/parameters/enable
Y

/sys/module/thinkpad_acpi/parameters/experimental
0

/sys/module/thinkpad_acpi/parameters/fan_control
Y

/sys/module/thinkpad_acpi/parameters/force_load
N

/sys/module/thinkpad_acpi/parameters/id
ThinkPadEC

/sys/module/thinkpad_acpi/parameters/index
-536870912

/sys/module/thinkpad_acpi/parameters/software_mute
Y

/sys/module/thinkpad_acpi/parameters/volume_capabilities
0

/sys/module/thinkpad_acpi/parameters/volume_control
N

/sys/module/thinkpad_acpi/parameters/volume_mode
3

**Comment by vmatare** [comment]
Ok, thanks for getting back with the info. Since you have `level: 7` and `level: disengaged` in `/proc/acpi/ibm/fan` I'd say that thinkfan is doing exactly what it's supposed to do. That is, write these things into that file at the given temperatures. Whatever happens (or doesn't happen) after that is the responsibility of the `thinkpad_acpi` kernel module and the embedded controller firmware. Since I have never hear about such a severe bug in `thinkpad_acpi`, I'd guess that either something is wrong with your firmware or with your fan itself. You can try doing a BIOS update if you haven't already. Also, is your fan making any noises like whining, clacking or rattling? In that case you might have worn out bearings and will need to get a replacement fan. If it's neither of those things I fear I'm out of ideas :-/

**Comment by fakamaz** [comment]
Well, here's a thing. I have a dual boot, and under Windows there's another similar app which controls fan. And it's works just fine! As in it spins on a max speed and I do hear the noise of the fan...

Under Linux - nothing. So it's definitely not a fan problem. 

I was thinking that maybe that Windows app could interfere with Linux, but I'm not sure if it's even possible... On the other hand it does change fan control from bios to app settings.

**Comment by vmatare** [comment]
So that would mean that your hardware must be OK, and the only thing left is maybe some weird quirk in the interaction of `thinkpad_acpi` and your firmware. A BIOS update will update the embedded controller firmware, as well, so that's definitely worth trying. Other than that, you're also running a very old version of thinkfan, so you could try using [the latest release](https://github.com/vmatare/thinkfan/archive/refs/tags/1.3.1.tar.gz). However since I'm fairly certain that thinkfan is working correctly here, that would be a shot in the dark. Another last-resort experiment would be to use a sysfs `pwm*` file to control the fan instead of `/proc/acpi/ibm/fan`. Normally that shouldn't make a difference, but in your case all bets are off I guess...

**Comment by fakamaz** [comment]
Thank you for all your tips, I'll try this out and let you know. Just curious though, how do I check which version of thinkfan I'm currently using?

**Comment by vmatare** [comment]
Hi @fakamaz,

1. thinkfan should output its version when you run `thinkfan -h`. Be aware though that the thinkfan version 0.9.3 falsely reports its version as 0.9.1.
2. To compile the current version, you either need to have the development files of `libyaml-cpp` installed or you need to disable YAML support with `-DUSE_YAML=false`. Recent versions support a new, more powerful YAML-based config syntax if you're interested. But your old config should also continue to work as-is, not matter of you disable YAML or not.

**Comment by fakamaz** [comment]
Got it to compile with -DUSE_YAML=false and the version seems to be current 1.3.1! Thanks. 

Now I actually feel a slightly warm wind coming on 57/60+ C; will test it out on higher temps.

What about **pwm** - I just have to replace tp_fan with pwm in the same line, right?

**Comment by fakamaz** [comment]
Hmm, it seems the configuration now doesn't match was was used before, see below please:

systemctl status thinkfan.service

● thinkfan.service - thinkfan 1.3.1
     Loaded: loaded (/usr/local/lib/systemd/system/thinkfan.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/thinkfan.service.d
             └─override.conf
     Active: inactive (dead) since Wed 2022-07-27 11:25:05 CEST; 32min ago
   Main PID: 1346 (code=exited, status=0/SUCCESS)

Jul 26 20:32:13 -ThinkPad-L430 systemd[1]: Starting simple and lightweight fan control program...
Jul 26 20:32:13 -ThinkPad-L430 thinkfan[1309]: thinkfan 0.9.1 starting...
Jul 26 20:32:13 -ThinkPad-L430 systemd[1]: Started simple and lightweight fan control program.
Jul 27 11:25:05 -ThinkPad-L430 thinkfan[1346]: /proc/acpi/ibm/fan: No such file or directory
Jul 27 11:25:05 -ThinkPad-L430 thinkfan[1346]: Cleaning up and resetting fan control.
Jul 27 11:25:05 -ThinkPad-L430 thinkfan[1346]: /proc/acpi/ibm/fan: No such file or directory
Jul 27 11:25:05 -ThinkPad-L430 systemd[1]: thinkfan.service: Succeeded.
(base) -ThinkPad-L430:~$ sudo thinkfan -n
ERROR: ~TpFanDriver: Resetting fan control in /proc/acpi/ibm/fan: No such file or directory
ERROR: init: Initializing fan control in /proc/acpi/ibm/fan: No such file or directory

**Comment by vmatare** [comment]
So, one by one:
- For documentation of the legacy config syntax you're using, take a look at the man page: `man thinkfan.conf.legacy`. You'll need to look at the `pwm_fan` keyword under the `FANS` section and then you'll need to modify your fan levels to range from 0 to 255 instead of 0 to 7.
- The `watchdog ping` you see is like a deadman's switch on the `thinkpad_acpi` module. Even if the fan speed doesn't change, thinkfan regularly lets the kernel know that it's alive. That way, when thinkfan crashes or freezes, automatic fan control will kick in.
